let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "The Flash",
    price: 45,
    desc: " Đồ chơi được kiểm định an toàn chất lượng theo quy chuẩn Việt Nam. Chất liệu: Nhựa Cứng An Toàn",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Iron Man",
    price: 100,
    desc: "Có các khớp linh hoạt. Kích thích sự sáng tạo, tư duy của bé. Nhựa cao cấp an toàn cho trẻ.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Black Widow",
    price: 25,
    desc: "Mô hình có khớp (Action Figure) có thể tạo hình với nhiều tư thế.Sản phẩm có vỏ hộp, kèm theo nhiều phụ kiện.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Hulk",
    price: 300,
    desc: "Chất liệu nhựa cao cấp, bền màu, an toàn cho bé.Có thể gắn các vũ khí vào vị trị lưng của Hulk.",
    img: "images/img-4.jpeg",
  },
  {
    id: "thyfhcbcv",
    name: "Áo Marvel",
    price: 300,
    desc: "Chất liệu vải mềm , thấm hút mồ hôi tốt, thoáng mát cho mùa hè.",
    img: "images/img-5.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Áo Marvel",
    price: 300,
    desc: "Chất liệu vải mềm , thấm hút mồ hôi tốt, thoáng mát cho mùa hè.",
    img: "images/img-6.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Áo Marvel",
    price: 300,
    desc: "Chất liệu vải mềm , thấm hút mồ hôi tốt, thoáng mát cho mùa hè.",
    img: "images/img-7.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Áo Marvel",
    price: 300,
    desc: "Chất liệu vải mềm , thấm hút mồ hôi tốt, thoáng mát cho mùa hè.",
    img: "images/img-8.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mũ Marvel",
    price: 300,
    desc: "Chất liệu : Vải cao cấp. Form mũ cứng. Size có thể chỉnh tùy theo ý muốn.",
    img: "images/img-9.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mũ Marvel",
    price: 300,
    desc: "Chất liệu : Vải cao cấp. Form mũ cứng. Size có thể chỉnh tùy theo ý muốn.",
    img: "images/img-10.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mũ Marvel",
    price: 300,
    desc: "Chất liệu : Vải cao cấp. Form mũ cứng. Size có thể chỉnh tùy theo ý muốn.",
    img: "images/img-11.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mũ Marvel",
    price: 300,
    desc: "Chất liệu : Vải cao cấp. Form mũ cứng. Size có thể chỉnh tùy theo ý muốn.",
    img: "images/img-12.jpg",
  },
];
